// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LocalCommunityBoard.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddImageUrlToAnnouncements : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "image_url",
                table: "Announcements",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "image_url",
                table: "Announcements");
        }
    }
}
